{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "vergate.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vergate.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "vergate.secretName" . }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.data | nindent 4 }}
{{- end }}
